/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vplfcmnsbiunkycnpgat"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwbGZjbW5zYml1bmt5Y25wZ2F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5NjcwMzgsImV4cCI6MjA4NTU0MzAzOH0.E-jxsZX4Bzxel11JuJbOwaf_B_c5ASpXB9eRUg-4WlI"